import ConfigParser, tr_definitions, shutil, os

synced_folder_name = 'cam%02d_video_r' # cam01_video_r
info_file_template = "#\n# File generated by build_directory.py\n#\n\n# trial info\n# trial number, onset, offset\n1,-1,-1\n\n# sensor\n# recording time\n# hour, min, sec, ms\n-1,-1,-1,-1\n\n# speech\n# recording time\n# hour, min, sec, ms, rate\n%s\n\n# video cam03\n# hour, min, sec, ms, rate\n%s"
additional_folders = ['derived', 'extra_p', 'speech_transcription_p']

def main():
    config = ConfigParser.ConfigParser()
    config.read(tr_definitions.config_name)
    
    files = os.listdir('.')
    for i in range(0,100):
        check_name = 'cam%02d' % i
        for f in files:
            if check_name in f and '.' in f:
                tr_definitions.make_folder_bak(synced_folder_name % i)
                print("moving file")
                shutil.move(f, synced_folder_name % i)
                break
    
    for i in range(0,len(additional_folders)-1):
        foldername = additional_folders[i]
        tr_definitions.make_folder_bak(foldername)
        
if __name__ == "__main__":
    main()