import ConfigParser, datetime, glob, shutil, subprocess, os

'''
extract_frames_tr.py
synchronize videos and extract frames from videos using ffmpeg
ffmpeg must be on the system paths, or be able to be called from this directory
script must be called from the directory containing the subject video files and sync.txt file, for example,

movie_cam01.MOV
movie_cam02.AVI
sync.txt
..
.

Calling the script will create a separate subject directory, e.g.,
X:\multisensory\experiment_12\included\__20151201_12888\
where X is the drive letter of the directory containing the subject video files
The output of ffmpeg will be placed into this directory

Cameras should be denoted with "cam#" (# has width 2 digits, so ..08, 09, 10, 11,..) in their names.
This will determine the folder name of the synced video and extracted frames.

sync.txt is a comma-delimited file including synchronized timing information across the videos
e.g.

#expID,kidID,dateofexp,
12,12888,20151201,
#camID,timestamp,tosync,toextract
1,03:25.773,1,1
2,03:25.734,1,1
3,03:25.423,1,1
#camID,extract_begin,extract_end,
1,01:00.000,2:00.000,
#camID,sync_begin,sync_end,
1,03:50.000,4:50.000,

first 2 lines dictate subject information; experiment ID, KID database ID, and the experiment date in YYYYMMDD format
camID refers to the different cam#_video_r folders
timestamp is a synchronous reference point across the videos.
Meaning, these points should all refer to the same moment in real-time.

tosync and toextract is a 1 or 0 indicating whether to output extracted frames or synchronous video

extract_begin and extract end designate the time range of the extract frames.
This is useful for only extracting a subset of the possible frames.

sync_begin and sync_end designate the time range to sync the videos.

Notes:
camID should always point to the specific camera used to determine the extract/sync time ranges.
In the above example, cam01_video_r was used to determine the range.

this script will also create empty folders and files for camera IDs not in current use, but intended to use later.

When re-running the script, it will move sync.txt from source to destination

'''

# CONFIGURATION
synced_folder_name = 'cam%02d_video_r' # cam01_video_r
frames_folder_name = 'cam%02d_frames_p' # cam01_frames_p
main_audio_folder_name = 'speech_r'
sub_audio_folder_name = 'speech_r\sub'
info_file_name = '__%s_%s_info.txt' # __20160101_16999
frame_rate = "30" # frame rate of output videos and frames
audio_rate = "44100"
additional_folders = ['derived', 'extra_p', 'speech_transcription_p']
additional_cameras = [] # camera folder to create; e.g. cam01_*, cam02_*,...,cam10_*
info_file_template = "#\n# File generated by move_tr.py\n#\n\n# trial info\n# trial number, onset, offset\n1,-1,-1\n\n# sensor\n# recording time\n# hour, min, sec, ms\n-1,-1,-1,-1\n\n# speech\n# recording time\n# hour, min, sec, ms, rate\n%s\n\n# video cam03\n# hour, min, sec, ms, rate\n%s"

def time_duration(t1,t2):
	datetimes = [t1, t2]
	datetimes = [datetime.datetime.strptime(x, '%M:%S.%f') for x in datetimes]
	duration = datetimes[1] - datetimes[0]
	duration = str(duration)
	return duration, datetimes

def copy_if_newer(filename, directory):
	fullfilename = os.path.join(directory, filename)
	if os.path.exists(fullfilename) == True:
		if os.stat(filename).st_mtime - os.stat(fullfilename).st_mtime > 1:
			shutil.copy2(filename, directory)
	else:
		shutil.copy2(filename, directory)

def make_folder_bak(foldername):
	if os.path.exists(foldername) == False:
		os.makedirs(foldername)
	else:
		if len(os.listdir(foldername)) > 0:
			i = 1
			while True:
				bakfoldername = foldername + '_bak%d' % i
				if os.path.exists(bakfoldername) == True:
					i += 1
				else:
					break
			os.rename(foldername, bakfoldername)
			os.makedirs(foldername)

def main():
	config = ConfigParser.ConfigParser()
	config.read("config.ini")

	expID = config.get("subinfo", "expID")
	kidID = config.get("subinfo", "kidID")
	dateofexp = config.get("subinfo", "dateofexp")
	
	syncpoints = config.items("syncpoints")
	camID = [i[0] for i in syncpoints]
	timestamps = [i[1] for i in syncpoints]

	synccamID = config.get("syncvideo", "camID")
	sync_begin = config.get("syncvideo", "begin")
	sync_end = config.get("syncvideo", "end")

	extractcamID = config.get("extractframes", "camID")
	extract_begin = config.get("extractframes", "begin")
	extract_end = config.get("extractframes", "end")

	tosync = config.get("inputcontrol", "tosync")
	toextract = config.get("inputcontrol", "toextract")
	toaudio = config.get("inputcontrol", "toaudio")
	tosync = tosync.split(",")
	tosync = [x.strip(" ") for x in tosync]
	toextract = toextract.split(",")
	toextract = [x.strip(" ") for x in toextract]
	toaudio = toaudio.split(",")
	toaudio = [x.strip(" ") for x in toaudio]

	extractidx = camID.index(extractcamID)
	syncidx = camID.index(synccamID)

	# convert strings to datetime objects so that offsets can be calculated
	datetimes = [datetime.datetime.strptime(x, '%M:%S.%f') for x in timestamps]
	extractoffsets = [x-datetimes[extractidx] for x in datetimes]
	syncoffsets = [x-datetimes[syncidx] for x in datetimes]

	extractduration, extractdatetimes = time_duration(extract_begin, extract_end)
	syncduration, syncdatetimes = time_duration(sync_begin, sync_end)

	if os.path.exists(main_audio_folder_name) == False:
		os.mkdir(main_audio_folder_name)

	if os.path.exists(sub_audio_folder_name) == False:
		os.mkdir(sub_audio_folder_name)

	for i in range(0,len(additional_folders)-1):
		foldername = additional_folders[i]
		make_folder_bak(foldername)

	print(camID)
	print(toextract)
	print(tosync)
	print(toaudio)
		
	for i in range(0, len(camID)):

		outdirvideo = synced_folder_name % int(camID[i])
		outdirframes = frames_folder_name % int(camID[i])
		if camID[i] in toaudio and toaudio.index(camID[i]) == 0:
			outdiraudio = main_audio_folder_name
		else:
			outdiraudio = sub_audio_folder_name
			
		# ffmpeg has the ability to have multiple outputs for a single input, which should speed up processing time
		# therefore, the below subcommands are determined and then combined for a single subprocess call to ffmpeg
		if camID[i] in toextract or camID[i] in tosync:
			videoname = glob.glob('*cam%02d*.*' % int(camID[i]))[0]
			if len(videoname) > 0:
				extract_starttime = extractdatetimes[0] + extractoffsets[i]
				extract_starttime_str = extract_starttime.strftime('%H:%M:%S.%f')
				
				sync_starttime = syncdatetimes[0] + syncoffsets[i]
				sync_starttime_str = sync_starttime.strftime('%H:%M:%S.%f')
			
				subcommand1 = ""
				subcommand2 = ""
				subcommand3 = ""
				
				if camID[i] in toextract:
					make_folder_bak(outdirframes)
					contents = os.listdir(outdirframes)
					if len(contents) > 1:
						raise ValueError("error on camID %s: frames folders must not already contain files" % camID[i])
					subcommand1 = ' -ss ' + extract_starttime_str + ' -t ' + extractduration + ' -qscale:v 2 -r '+ frame_rate + ' -vf scale=-1:480 ' + outdirframes + '\img_%d.jpg'
					
				if camID[i] in tosync:
					make_folder_bak(outdirvideo)
					contents = os.listdir(outdirvideo)
					if len(contents) > 0:
						raise ValueError("error on camID %s: video folders must not already contain files" % camID[i])
					outputvideoname = videoname.split('.')
					outputvideoname = outputvideoname[0] + '.mov'
					subcommand2 = ' -ss ' + sync_starttime_str + ' -t ' + syncduration + ' -vcodec mpeg4 -acodec pcm_s16le -qscale:v 2 -r ' + frame_rate + ' -vf scale=-1:480 ' + outdirvideo + '\\' + outputvideoname
					
				if camID[i] in toaudio:
					outputaudioname = videoname.split('.')
					outputaudioname = outputaudioname[0] + '.wav'
					subcommand3 = ' -ss ' + sync_starttime_str + ' -t ' + syncduration + ' -vn -ar ' + audio_rate + ' -ac 1 -ab 192k -f wav -acodec pcm_s16le ' + outdiraudio + '\\' + outputaudioname
				
				command = 'ffmpeg -y -i ' + videoname + subcommand1 + subcommand2 + subcommand3
				print(command)
				#subprocess.call(command.split(' '))
				
	for i in additional_cameras:
		outdirvideo = synced_folder_name % i
		if os.path.exists(outdirvideo) == False:
			os.mkdir(outdirvideo)
		outdirframes = frames_folder_name % i
		if os.path.exists(outdirframes) == False:
			os.mkdir(outdirframes)
	
	info_file = info_file_template % ('%d,%d,%d,%d,%s' % (sync_starttime.hour, sync_starttime.minute, sync_starttime.second, sync_starttime.microsecond/1000, audio_rate), '%d,%d,%d,%d,%s' % (extract_starttime.hour, extract_starttime.minute, extract_starttime.second, extract_starttime.microsecond/1000, frame_rate))
	fid = open("__" + dateofexp + "_" + kidID + "_info.txt", "w")
	fid.write(info_file)
	fid.close()
if __name__ == "__main__":
	main()